stages:
  - build
  - test

default:
  image: maven:3.9-eclipse-temurin-21

compile:
  stage: build
  script:
    - mvn -B package -DskipTests
    - ls -lh target/*.jar

package-check:
  stage: test
  script:
    - ls -lh target/*.jar
